### ISSUE TITLE
Remove dependency from CFBundleName in plist

### ISSUE THREAD

**Issue by kleuter** [akeru-inc/xcnotary#13]
All .app bundles that I encounter no longer have it (including our apps an Apple itself)

It's a legacy key with max 15 characters which is not even used by the tool ("CFBundleIdentifier" is used I suppose)

What is worse: when the plist doesn't have CFBundleName - the tool **crash**es:

```
RUST_BACKTRACE=full xcnotary notarize "thetool.app" -d XXX -k YYY
Processing...

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { kind: Serde("missing field `CFBundleName`"), file_position: None } }', src/util/plist/mod.rs:6:28
stack backtrace:
   0:        0x104bab354 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
   1:        0x104bcf0e0 - core::fmt::write::h94ae1e793baa7a00
   2:        0x104ba439b - std::io::Write::write_fmt::h5c716758fdc3057f
   3:        0x104bad575 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
   4:        0x104bad2b7 - std::panicking::default_hook::heae8b62897b351dc
   5:        0x104badb15 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
   6:        0x104bad6ab - std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
   7:        0x104bab7c8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
   8:        0x104bad66a - _rust_begin_unwind
   9:        0x104bde84f - core::panicking::panic_fmt::hcdc9362d34d55302
  10:        0x104bde755 - core::option::expect_none_failed::hef0458611b13747b
  11:        0x1048badf3 - xcnotary::main::hf99224fe654abb34
  12:        0x1048bb0ca - std::sys_common::backtrace::__rust_begin_short_backtrace::h3796f84a44bcf507
  13:        0x1048bb12c - std::rt::lang_start::{{closure}}::h43d4e0f376c8876a
  14:        0x104badeb0 - std::rt::lang_start_internal::hd0c760d47f593c0a
  15:        0x1048bb089 - _main
```

**Comment by kleuter** [comment]
```
RUST_BACKTRACE=full xcnotary notarize "thetool.app" -d XXX -k YYY
Processing...

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { kind: Serde("missing field `CFBundleName`"), file_position: None } }', src/util/plist/mod.rs:6:28
stack backtrace:
   0:        0x104bab354 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
   1:        0x104bcf0e0 - core::fmt::write::h94ae1e793baa7a00
   2:        0x104ba439b - std::io::Write::write_fmt::h5c716758fdc3057f
   3:        0x104bad575 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
   4:        0x104bad2b7 - std::panicking::default_hook::heae8b62897b351dc
   5:        0x104badb15 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
   6:        0x104bad6ab - std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
   7:        0x104bab7c8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
   8:        0x104bad66a - _rust_begin_unwind
   9:        0x104bde84f - core::panicking::panic_fmt::hcdc9362d34d55302
  10:        0x104bde755 - core::option::expect_none_failed::hef0458611b13747b
  11:        0x1048badf3 - xcnotary::main::hf99224fe654abb34
  12:        0x1048bb0ca - std::sys_common::backtrace::__rust_begin_short_backtrace::h3796f84a44bcf507
  13:        0x1048bb12c - std::rt::lang_start::{{closure}}::h43d4e0f376c8876a
  14:        0x104badeb0 - std::rt::lang_start_internal::hd0c760d47f593c0a
  15:        0x1048bb089 - _main
```

**Comment by davidvartan** [comment]
This key was only remaining from a legacy version of the tool, so I went ahead and removed it. Thanks for the report!

**Comment by kleuter** [comment]
Thanks a lot.
